# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Back-end CD

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        name: check diff
        run: |
          diff=$(git diff origin/${GITHUB_BASE_REF} -- packages/backend)
          if [ -z "$diff" ]
          then
            echo "no changes"
            echo "::set-output name=changed::false"
          else
            echo "changes detected"
            echo "::set-output name=changed::true"
          fi

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/master.key
          chmod 600 ~/.ssh/master.key
          cat >>~/.ssh/config <<END
          Host master
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/master.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_USERNAME }}
          SSH_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PROD_HOST }}

      - name: Fetch Repos
        run: ssh master 'cd repos/workout-counter && git fetch && git checkout master && git reset --hard origin/master'

      - name: Run Install
        run: ssh master 'cd repos/workout-counter && yarn install'

      - name: Reload PM2
        run: ssh master 'cd repos/workout-counter/packages/backend && sudo pm2 start ecosystem.config.js'
