# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Front-end CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/develop.key
          chmod 600 ~/.ssh/develop.key
          cat >>~/.ssh/config <<END
          Host develop
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/develop.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_USERNAME }}
          SSH_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PROD_HOST }}

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Sync build files to server
        run: rsync -avz ./build/ develop:/home/$SSH_USER/www/data
        env:
          SSH_USER: ${{ secrets.PROD_USERNAME }}
