# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Front-end CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      # - name: Run lint
      #   run: yarn run lint

      - name: Run tests
        run: yarn test
